name: deka_appps_ios
description: DekaApppsIos
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #state management
  flutter_bloc: ^8.1.2

  #comparing dart objects
  equatable: ^2.0.5

  #service locator
  get_it: ^7.6.0

  #dateFormat
  intl: ^0.18.1

  #Database
  floor: ^1.4.2

  #make request to api
  retrofit: ^3.3.1

  #Hooks
  flutter_hooks: ^0.18.3

  #chached image
  cached_network_image: ^3.2.0

  #workmanager
  workmanager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  retrofit_generator: 3.0.1+1
  floor_generator: 1.2.0
  build_runner: 2.1.2

flutter:
  uses-material-design: true

  fonts:
    - family: Nunitosans
      fonts:
        - asset: assets/fonts/nunitosans/Nunitosans.ttf
        - asset: assets/fonts/nunitosans/Nunitosans-Bold.ttf
          weight: 700
        - asset: assets/fonts/nunitosans/Nunitosans-Light.ttf
          weight: 300

  assets:
    - assets/images/gif_no_data.gif
    - assets/images/img_background_factory.jpg
