Map<int, String> migrationScripts = {
  1: '''CREATE TABLE IF NOT EXISTS `profile` (
        `userId` TEXT, 
        `nik` TEXT, 
        `username` TEXT, 
        `password` TEXT, 
        `typeuserCode` TEXT, 
        `typeuserName` TEXT, 
        `code` TEXT, 
        `name` TEXT, 
        `address` TEXT, 
        `tempatLahir` TEXT, 
        `tglLahir` TEXT, 
        `tglMasuk` TEXT, 
        `email` TEXT, 
        `phone1` TEXT, 
        `phone2` TEXT, 
        `photo` TEXT, 
        `photoKtp` TEXT, 
        `noKtp` TEXT, 
        `typeuserId` TEXT, 
        `divisiCode` TEXT, 
        `jabatanCode` TEXT, 
        `deviceId` TEXT, 
        `deviceBrand` TEXT, 
        `deviceType` TEXT, 
        `firebaseId` TEXT, 
        `costCenterCode` TEXT, 
        `lokasi` TEXT, 
        `organizationLevel` TEXT, 
        PRIMARY KEY (`userId`))''',
  2: '''ALTER TABLE `profile` ADD `status` INTEGER''',
  3: '''ALTER TABLE `profile` ADD `statusKirim` INTEGER''',
  4: '''ALTER TABLE `profile` ADD `createdAt` TEXT''',
  5: '''ALTER TABLE `profile` ADD `updatedAt` TEXT''',
  6: '''CREATE TABLE IF NOT EXISTS `pengaturan_autocode_android` (
        `code` TEXT, 
        `value` TEXT, 
        `count` TEXT,
        `status` INTEGER, 
        `statusKirim` INTEGER, 
        `createdAt` TEXT, 
        `updatedAt` TEXT,
        PRIMARY KEY (`code`))''',
  7: '''CREATE TABLE IF NOT EXISTS `master_reason` (
        `code` TEXT, 
        `name` TEXT, 
        `type` INTEGER,
        `keterangan` TEXT,
        `potong_cuti` TEXT,
        `status` INTEGER, 
        `statusKirim` INTEGER, 
        `createdAt` TEXT, 
        `updatedAt` TEXT,
        PRIMARY KEY (`code`))''',
  8: '''CREATE TABLE IF NOT EXISTS `master_reason_type` (
        `id` INTEGER, 
        `name` TEXT,
        `status` INTEGER, 
        `statusKirim` INTEGER, 
        `createdAt` TEXT, 
        `updatedAt` TEXT,
        PRIMARY KEY (`id`))''',
};